# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install flask
  - pip install flask-ci

# Run the unit test
script:
  - python app/app.py ci